version : "3.9"

services:

  backend:
    build: ./backend
    container_name: backend-server
    env_file:
      - ./backend/.env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: postgres_db_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: